Makes the bell silent
contour-terminal/contour pull request #1159
Opened 2023-08-10 15:30 UTC by Utkarsh-khambra

Adds a config option `bell` under profile which if set to true makes bell silent.

2023-08-10 16:04 UTC, Utkarsh-khambra commented on src/contour/Config.h
> +    }
This is silence gcc error warning about possible nullptr deference.

2023-08-10 16:18 UTC, Yaraslaut requested changes

2023-08-10 16:25 UTC, Yaraslaut commented
Also, we need to update documentation here  [profiles.md](https://github.com/contour-terminal/contour/blob/master/docs/configuration/profiles.md)

2023-08-11 09:09 UTC, christianparpart requested changes
LGTM, only very minors, that might make sense to apply. What do you think?

2023-08-11 09:09 UTC, christianparpart commented on docs/configuration/profiles.md
> +configuration option determines whether or not BEL character '\a' or 0x07 produces audible sound or not.
```suggestion
Configuration option determines whether or not `BEL` character `\a` or `0x07` produces audible sound or not.
```

2023-08-11 09:09 UTC, christianparpart commented on docs/configuration/profiles.md
>  configuration option defines the class part of the WM_CLASS property of the terminal window. The WM_CLASS property is a standard X11 property used to identify and classify windows by their class and
```suggestion
Configuration option defines the class part of the `WM_CLASS` property of the terminal window. The `WM_CLASS` property is a standard X11 property used to identify and classify windows by their class and instance.
```

2023-08-11 12:39 UTC, Utkarsh-khambra commented
I read the suggestion making bell to be `off` , `default` or `path`  to make more configurable. Working on that.

2023-08-13 18:47 UTC, Yaraslaut requested changes
Looks like not all wav files are good for a bell sound, i just downloaded random one from https://mixkit.co/free-sound-effects/bell/  and it didn't work :(

2023-08-14 03:18 UTC, Utkarsh-khambra commented
@Yaraslaut can link a specific one? I tried a bunch of 'em from here already and they worked.

2023-08-14 07:42 UTC, christianparpart commented on src/contour/ui.template/Terminal.qml
> +        audioOutput: bellAudioOutput
Only the `.qml.in` files were supposed to be git-tracked in the `ui.template` folder. You can basically drop the changes here and it'll have no affect.

In a future/other PR we should actually get rid of these. :)

2023-08-14 07:44 UTC, christianparpart commented on src/contour/contour.yml
> +        # Determines if BEL character sound is "off" or "default" or is given by file at "path"
I think we can make this a multi-line comment, specifically describing each value.

2023-08-14 07:44 UTC, christianparpart commented on src/contour/ContourGuiApp.cpp
> +        qmlEngine_->rootObjects().first()->findChild<QObject*>("Bell")->setProperty("source", path);
Can `qmlEngine_->rootObjects().first()->findChild<QObject*>("Bell")` return `nullptr`? If so, we should dereference it only if it's assured to be non-null.

2023-08-14 07:45 UTC, christianparpart commented on src/contour/ContourGuiApp.cpp
> +        qmlEngine_->rootObjects().first()->findChild<QObject*>("BellAudioOutput")->setProperty("muted", true);
same here (like below, sorry for the inverse comments) :)

2023-08-14 07:47 UTC, christianparpart requested changes
Sorry, I should have used the review functionality from the start. :)

2023-08-14 07:47 UTC, christianparpart commented on src/contour/Config.h
> +#include "crispy/assert.h"
```suggestion
#include <crispy/assert.h>
```

2023-08-18 13:14 UTC, christianparpart approved these changes
Many thanks

2023-08-18 13:15 UTC, merged