Some minor fixes and updates
contour-terminal/contour pull request #1290
Opened 2023-10-17 17:21 UTC by Yaraslaut

Fix build with g++ (GCC) 13.2.1 and range, as well as some errors from gentoo

2023-10-18 15:07 UTC, christianparpart requested changes

2023-10-18 15:07 UTC, christianparpart commented on src/crispy/read_selector.h
> +    Require(written > 0);
same

2023-10-18 16:04 UTC, Yaraslaut commented on src/vtbackend/InputGenerator.cpp
>      }
Sure, this return also works, g++ is complaining while compiling with pedantic

2023-10-18 20:55 UTC, christianparpart approved these changes
so far so good, but still in draft mode :-)

2023-10-19 05:20 UTC, christianparpart approved these changes

2023-10-19 11:34 UTC, merged