Replace all occurrences of OS/X
contour-terminal/contour pull request #1462
Opened 2024-02-10 21:57 UTC by fingolfin

The Macintosh operating system underwent many name changes over the years,
from being nameless to "System" to "Mac OS" to "OS X" to "macOS".

But at no point in time was it ever called "OS/X" :-)

2024-02-10 22:13 UTC, uspasojevic96 requested changes
Did a quick review, what I would NOT do is to edit existing changelog, but add new entry for the change of naming

2024-02-10 22:13 UTC, uspasojevic96 commented on docs/configuration/advanced/misc.md
> +- cocoa       Used to be run on Mac macOS.
```suggestion
- cocoa       Used to be run on macOS.
```

2024-02-10 23:15 UTC, christianparpart commented
Many thanks, @fingolfin.

I think I'm used to name it like that from the time it was named like that (just without the slash):

![image](https://github.com/contour-terminal/contour/assets/56763/7a64ee0a-232e-41c5-89da-0ea42faf7578) [[1]](https://en.wikipedia.org/wiki/MacOS)

Not sure were the slash i coming from, in my memories :)

2024-02-10 23:34 UTC, fingolfin commented on docs/configuration/advanced/misc.md
> +- cocoa       Used to be run on Mac macOS.
Thanks

2024-02-10 23:37 UTC, fingolfin commented
> Did a quick review, what I would NOT do is to edit existing changelog,

But why not? Would you not fix typos in them either?

> but add new entry for the change of naming

OK, if you want a changelog entry for a typo fix, I am happy to add it -- except I have no idea how. I am guessing `metainfo.xml` might be the changelog file (though I am not sure given its name)? But what is the format, where would this be added?

2024-02-10 23:56 UTC, christianparpart commented
https://github.com/contour-terminal/contour/blob/cdb2e16d29fff252a3b95977c9dc03fd2f96e2a0/metainfo.xml#L107-L113

Hey. This is going to be the changelog for the next release. You can simply add yourself at the end of it.

Changelogs can of course be typo-fixed, but I remember from other big open source projects that change logs are only about to be changed for present/future entries, not touching past entries. So I think that's a philosophy thing :)

2024-02-13 07:32 UTC, christianparpart commented
Hey @fingolfin. Can I help you with anything?

2024-02-13 08:03 UTC, fingolfin commented
I don't time to work on this outside of weekends. Anyway, this is a trivial search&replace change. Feel free to finish the PR in whichever way you want it, or to close it / do your own version of it.

2024-02-18 21:40 UTC, christianparpart approved these changes

2024-02-18 21:47 UTC, merged

2024-02-18 22:06 UTC, christianparpart commented
I've added the changelog entry after the merge. Many thanks @fingolfin for your contribution and support. :-)