Don't use absolute path to contour in contour.desktop
contour-terminal/contour pull request #502
Opened 2021-11-15 21:17 UTC by data-man

Many apps uses this way.
E.g. I **always** install my compiled binaries to `/usr/local/bin`.

2021-11-15 23:22 UTC, christianparpart commented
> Many apps uses this way. E.g. I **always** install my compiled binaries to `/usr/local/bin`.

Exactly, and that's why both are wrong, because there might be a executable X in /bin, /usr/bin/, /usr/local/bin, and in $HOME/bin (I have a lot in $HOME/usr/bin for example).

I think the best solution is to use a generator and have it point to an absolute path but based on`${CMAKE_INSTALL_PREFIX}/bin`. This way we've fixed them all. ;)

2021-11-15 23:24 UTC, christianparpart requested changes

2021-11-15 23:24 UTC, christianparpart commented on src/contour/contour.desktop
> +Exec=contour
```suggestion
Exec=@CMAKE_INSTALL_PREFIX@/bin/contour
```
and then using a preprocessor / generator / `m4` to generate the actual .desktop file.

2021-11-16 09:56 UTC, data-man commented
> and that's why both are wrong

I strongly disagree, because hardcoded paths are evil! ;)
BTW, the recently added `contour-run.desktop` also uses only `contour`, so we have some inconsistency.

2021-11-16 10:42 UTC, christianparpart commented
> I strongly disagree, because hardcoded paths are evil! ;)

Is it really hard-coded if you generated it based on CMake configuration variables? :thinking:

2021-11-16 10:47 UTC, christianparpart commented
I just checked my .desktop files on my system. It's a mixed experience. So there's no common consensus either. But if you make it depending on CMAKE_INSTALL_PREFIX, you'd at least not depend on the users' correctly configured PATH env var.

2021-11-16 11:05 UTC, data-man commented
> Is it really hard-coded if you generated it based on CMake configuration variables?

Yes.
E.g. `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/sbin:/opt/bin` and `contour` installed to `/usr/bin`.

So I can create simple shell script `contour` in `/usr/local/bin with some `LD_PRELOAD` trick. It's flexible. :)

2021-11-16 11:13 UTC, uspasojevic96 commented
> > Is it really hard-coded if you generated it based on CMake configuration variables?
> 
> Yes. E.g. `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/sbin:/opt/bin` and `contour` installed to `/usr/bin`.
> 
> So I can create simple shell script `contour` in `/usr/local/bin` with some `LD_PRELOAD` trick. It's flexible. :)

I am confused here, if you specify the install path and it generates it in `.desktop` how would that be hardcoded?

2021-11-16 12:03 UTC, data-man commented
>  it generates it in .desktop how would that be hardcoded?

Just like now:
```
...
Exec=/usr/bin/contour
...
```

2021-11-16 12:04 UTC, christianparpart approved these changes
Maybe I'm not clearly expressing myself. But I'm fine for not fully qualifying for now.

2021-11-16 12:05 UTC, merged