WIP Add formatter
contour-terminal/contour pull request #587
Opened 2022-01-12 18:16 UTC by sebastianrakel

On arch the compiler fails on missing formatter, this PR should provide them

2022-01-13 11:16 UTC, christianparpart requested changes
Looks good. But maybe you want to try avoid unnecessary memory allocations by avoiding to use `std::vector` and use `std::array` instead.

Using member `at(index)` over `operator[](index)` also ensures you do not accidentally overflow as the `at(index)` member function will throw if out of bounds (the other will not).

2022-01-13 11:16 UTC, christianparpart commented on src/terminal/InputGenerator.h
> +      std::vector<std::string> key_values = {"F1","F2",
```suggestion
      static constexpr auto mappings = std::array{"F1","F2",
```

2022-01-13 11:16 UTC, christianparpart commented on src/terminal/InputGenerator.h
> +      return format_to(_ctx.out(), key_values[unsigned(_value)]);
```suggestion
      return format_to(_ctx.out(), mappings.at(static_cast<size_t>(_value)));
```

2022-01-13 11:16 UTC, christianparpart commented on src/terminal/InputGenerator.h
> +	"F3",
You can try running clang-format over this file to fix the indentation here. 

The command on the CLI would be something like: `clang-format -i  ./src/terminal/InputGenerator.h`

2022-01-13 21:51 UTC, christianparpart commented
FYI: I just realized that these are due to fmtlib being too new on Arch Linux. I just ran into the same problem locally when upgrading the Ubuntu 21.10 to 22.04 (dev). Do you want to finish this? Then just go ahead an remove the "WIP" prefix when done // mark this PR as "ready for review". :)

2022-01-14 09:56 UTC, sebastianrakel commented
> FYI: I just realized that these are due to fmtlib being too new on Arch Linux. I just ran into the same problem locally when upgrading the Ubuntu 21.10 to 22.04 (dev). Do you want to finish this? Then just go ahead an remove the "WIP" prefix when done // mark this PR as "ready for review". :)

I can try to fix the others but maybe i need some help

2022-01-14 11:09 UTC, christianparpart commented
> > FYI: I just realized that these are due to fmtlib being too new on Arch Linux. I just ran into the same problem locally when upgrading the Ubuntu 21.10 to 22.04 (dev). Do you want to finish this? Then just go ahead an remove the "WIP" prefix when done // mark this PR as "ready for review". :)
> 
> I can try to fix the others but maybe i need some help

just ping us on Discord #contour-dev, or say up until which point you want to do it, and I can do the rest :)

2022-01-14 18:43 UTC, christianparpart approved these changes
LGTM. Many thanks @sebastianrakel

2022-01-14 18:54 UTC, merged