Keep working directory same when new terminal is spawned
contour-terminal/contour pull request #759
Opened 2022-07-12 16:50 UTC by Utkarsh-khambra

- [ ]  cwd in Windows

2022-07-14 16:48 UTC, Utkarsh-khambra commented
[Here](https://stackoverflow.com/a/2967713) is a way to get cwd in windows. But don't have a windows pc to build it currently. So I'll leave it for future.

2022-07-21 18:28 UTC, christianparpart requested changes
I am so sorry for being late. The hotness must have taken my consciousness.

2022-07-21 18:28 UTC, christianparpart commented on src/contour/ContourGuiApp.cpp
> +    ContourGuiApp::_config = _config;
hm, okay, that's my bad for sure. We have multiple coding styles, sadly, and it's all my fault. I am sorry for that. It's probably best to simply rename the function parameter's `_config` to `config` and then have this line like `_config = config`.

2022-07-22 11:13 UTC, christianparpart approved these changes

2022-07-22 11:13 UTC, merged